services:
  redis:
    image: redis:7-alpine
    command: ["redis-server","--appendonly","no"]
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD","redis-cli","ping"]
      interval: 5s
      timeout: 3s
      retries: 10

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    environment:
      PORT: "4000"
      REDIS_URL: "redis://redis:6379"
      QUOTE_BASE: "https://quote-api.jup.ag"
      LITE_BASE: "https://lite-api.jup.ag"
      ULTRA_BASE: "https://api.jup.ag/ultra"
      JUP_ULTRA_KEY: ""
      ALLOWED_MINTS: ""
      BLOCKED_MINTS: ""
    ports:
      - "4000:4000"
    depends_on:
      redis:
        condition: service_healthy
