name: smoke

on:
  push:
    branches: [ main, release/** ]
  workflow_dispatch:

jobs:
  web-ok:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Check API /health
        env:
          API_BASE: https://cerberus-telegram-bot-tutorial.onrender.com
        run: |
          set -euo pipefail
          echo "Hitting $API_BASE/health"
          body="$(curl -fsS "$API_BASE/health")"
          echo "$body" | jq .
          # require JSON and ok==true
          echo "$body" | jq -e '.ok == true' >/dev/null
          echo "Health OK"

  build-web:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - name: Install & build web
        working-directory: web
        run: |
          npm ci
          printf 'NEXT_PUBLIC_API_BASE=%s\n' "https://cerberus-telegram-bot-tutorial.onrender.com" > .env.local
          npm run build
